### ISSUE TITLE
Handle readonly attributes as well as disabled ones

### ISSUE THREAD

**Issue by armchairdj** [jonathanong/form-to-object#12]
Great library - small, powerful and few dependencies.

However, it submits readonly form fields to the server.

It seems to handle disabled fields just fine and should require just a few additional `not(:read-only)` selectors to correctly ignore these fields.

Just a thought.

**Comment by jackmoore** [comment]
@armchairdj My understanding is that read-only values are normally submitted to the server as they are considered a "successful control". However, controls that are disabled are not considered successful. Here is the relevant part of the spec:
https://www.w3.org/TR/html401/interact/forms.html#h-17.12

**Comment by armchairdj** [comment]
You are 100% correct. I just ended up changing my FE to use disabled instead of read-only and adjusted my CSS accordingly. Thanks for teaching me something I didn't know despite 20+ years of front-end coding.
