### ISSUE TITLE
NPM package not working

### ISSUE THREAD

**Issue by tbleckert** [jonathanong/form-to-object#6]
The package form2obj on NPM is not working, the index.js file only contains this:

``` js
module.exports = require('./lib/form2obj');
```

**Comment by jackmoore** [comment]
This package is called `form-to-object` on NPM.  

It looks like 'form2obj' is a fork of this project, but the new author never updated the package.json to reflect that it was forked to a new repo.  Here is the repo for form2obj: https://github.com/i5ting/form2obj

**Comment by tbleckert** [comment]
Ah I see, thanks!
